# Build settings for the standalone C++ Monte Carlo samplers in this directory.
# Inputs are the compiler and Eigen include paths; make builds the matching
# executable from a same-named .cpp source using these flags.
#CXX=g++
#CXXFLAGS += -O3 -I${HOME}/local/include -std=c++11 -I. -DNDEBUG -g 
#CXXFLAGS += -O3 -I${HOME}/Programs/include -std=c++11 -I. -DNDEBUG  

#CXXFLAGS += -O3 -I${HOME}/local/include -std=c++11 -DNDEBUG
CXXFLAGS += -O3 -I${HOME}/Programs/include -std=c++11 -I. -DNDEBUG 

CXXFLAGS += -O3 -I${HOME}/local/include -std=c++11 -DNDEBUG

# Add the Eigen include directory to the flags
CXXFLAGS += -I${HOME}/eigen-3.3.9

LDLIBS = -lm


#is for comments
